apiVersion: v1
kind: Secret
metadata:
  name: connector-secrets
  namespace: instant-connector
  labels:
    app: instant-data-connector
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  POSTGRES_USER: Y29ubmVjdG9yX3VzZXI=  # connector_user
  POSTGRES_PASSWORD: cHJvZF9wYXNzd29yZF8xMjM=  # prod_password_123
  POSTGRES_REPLICA_USER: cmVwbGljYV91c2Vy  # replica_user
  POSTGRES_REPLICA_PASSWORD: cmVwbGljYV9wYXNzd29yZF8xMjM=  # replica_password_123
  
  # Redis credentials
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMTIz  # redis_password_123
  
  # Application secrets
  SECRET_KEY: c3VwZXJfc2VjcmV0X2tleV9jaGFuZ2VfbWVfaW5fcHJvZHVjdGlvbg==  # super_secret_key_change_me_in_production
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfY2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=  # encryption_key_change_me_in_production
  JWT_SECRET: and0X3NlY3JldF9jaGFuZ2VfbWVfaW5fcHJvZHVjdGlvbg==  # jwt_secret_change_me_in_production
  
  # External service credentials
  SENTRY_DSN: ""  # Add your Sentry DSN here
  NEW_RELIC_LICENSE_KEY: ""  # Add your New Relic license key here
  
  # SMTP credentials for notifications
  SMTP_HOST: c210cC5leGFtcGxlLmNvbQ==  # smtp.example.com
  SMTP_USER: bm90aWZpY2F0aW9uc0BleGFtcGxlLmNvbQ==  # notifications@example.com
  SMTP_PASSWORD: c210cF9wYXNzd29yZA==  # smtp_password
  SMTP_FROM_ADDRESS: bm90aWZpY2F0aW9uc0BleGFtcGxlLmNvbQ==  # notifications@example.com
  
  # Backup service credentials
  AWS_ACCESS_KEY_ID: ""  # Add your AWS access key ID
  AWS_SECRET_ACCESS_KEY: ""  # Add your AWS secret access key
  BACKUP_S3_BUCKET: ""  # Add your S3 bucket name
  
  # Monitoring credentials
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl8xMjM=  # grafana_admin_123

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ssl-certs
  namespace: instant-connector
  labels:
    app: postgres-fdw
    component: ssl
type: kubernetes.io/tls
data:
  # Replace with your actual SSL certificates (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # server.crt
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...  # server.key
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...   # ca.crt

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl-certs
  namespace: instant-connector
  labels:
    app: nginx
    component: ssl
type: kubernetes.io/tls
data:
  # Replace with your actual SSL certificates (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # nginx.crt
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...  # nginx.key