# Prometheus configuration for PostgreSQL FDW Data Connector - Development
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'instant-connector-dev'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerts.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Main application
  - job_name: 'instant-connector-app'
    static_configs:
      - targets: ['connector-app:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL database
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-fdw:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    # Use postgres_exporter if available
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    # Use redis_exporter if available
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Celery workers
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['celery-worker:8001']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 10s

  # Custom health check endpoint
  - job_name: 'health-checks'
    static_configs:
      - targets: ['connector-app:8000']
    scrape_interval: 60s
    metrics_path: /health
    scrape_timeout: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'health-check'

  # FDW-specific metrics
  - job_name: 'fdw-metrics'
    static_configs:
      - targets: ['connector-app:8000']
    scrape_interval: 60s
    metrics_path: /api/metrics/fdw
    scrape_timeout: 30s
    honor_labels: true

# Remote write configuration (optional, for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true